[package]
name = "virus-deobfuscator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.77"
base64 = "0.21.5"
flate2 = "1.0.28"
nom = "7.1.3"
nom-supreme = "0.8.0"
